# Generated by Django 4.1.10 on 2024-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_adhesion', models.DateField()),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant'), ('secretaire', 'Secretaire'), ('tresorier', 'Tresorier')], max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_adhesion', models.DateField()),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('enseignant', 'Enseignant'), ('secretaire', 'Secretaire'), ('tresorier', 'Tresorier')], max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subject_taught', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
