# Generated by Django 4.1.10 on 2024-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20)),
                ('date_of_issue', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('student_class', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='students/files/')),
            ],
        ),
    ]
