# Generated by Django 4.1.10 on 2024-06-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='place_of_birth',
            new_name='birth_place',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_issue',
            new_name='emission_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
