# Generated by Django 4.1.10 on 2024-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.FileField(upload_to='logos/'),
        ),
    ]
